// src/constants/errorCodes.ts
export const ERROR_CODES = {
  ENTITY_EXISTS: "ENTITY_EXISTS",
  RESEND_LIMIT: "RESEND_LIMIT",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;
